<head>  
<title>Spoilage Report Detailed</title></head>
<body>
<style>
    @page { size: landscape; }
    #issuance tr {
            background: transparent !important;
    }
    .report{
        border-bottom: 1px solid gray;
        border-right: none;
        border-left:none;
        border-top:none;

    }
    th{
        background-color: transparent!important;
    }

       body {
        font-family: 'Calibri',sans-serif;
        font-size: 12px;
    }

    .align-right {
        text-align: right;
    }

    .align-left {
        text-align: left;
    }

    .align-center {
        text-align: center;
    }

    .report-header {
        font-weight: bolder;
    }

          
      </style>

<div style="width:100%">
    <table width="100%" cellspacing="5" cellspacing="0">
        <tr>
            <td width="10%"  class="bottom"><img src="<?php echo base_url($company_info->logo_path); ?>" style="height: 90px; width: 120px; text-align: left;"></td>
            <td width="90%"  class="bottom" >
                <h3 class="report-header" style="margin-bottom: 0"><strong><?php echo $company_info->company_name; ?></strong></h3>
                <span><?php echo $company_info->company_address; ?></span><br>
                <span><?php echo $company_info->landline.'/'.$company_info->mobile_no; ?></span><br>
                <span><?php echo $company_info->email_address; ?></span><br>

            </td>
        </tr>
    </table>
<table style="font-family:tahoma;width: 100%;font-size: 12px;" id="report_header">
    <tbody>
        <tr>
            <td style="font-size:18px;font-weight:bold;border:none!important;" colspan="2"><center>Spoilage Report Detailed</center></td>
        </tr>
        <tr>
            <td style="width:15%">Date:</td>
            <td><?php echo $start_Date.' - '. $end_Date?></td>
        </tr>
        <tr>
            <td>Report Type:</td>
            <td><?php if($_GET['tid'] == 1 ){ echo 'Adjustments - OUT'; }else { echo 'Sales Returns - IN';}?></td>
        </tr>
    </tbody>
</table>
<br>
<?php foreach ($adjustments as $adjustment) { ?>
<table width="100%">
    <tr style="background-color: #82d1f5;" >
        <td ><?php echo $adjustment->adjustment_code; ?> 
<b>|</b> <font style="text-transform: capitalize;"> <?php echo $adjustment->customer_name; ?></font>
<b>|</b> <?php echo $adjustment->date_adjusted; ?></td>
    </tr>
</table>

<table id="tbl_pi_summary" class="table table-striped" cellspacing="0" width="100%">
    <thead class="">
    <tr>
        <th align="left">Product Code</th>
        <th align="left">Product Description</th>
        <th align="right">Quantity</th>
        <th align="right">Price</th>
        <th align="right">Total Amount</th>
    </tr>
    </thead>
    <tbody>
    <?php $total_qty = 0; $total_price = 0;
    foreach ($products as $product) { if($product->adjustment_id == $adjustment->adjustment_id){ ?>
    <tr>
        <td><?php echo $product->product_code ?></td>
        <td><?php echo $product->product_desc ?></td>
        <td  align="right"><?php echo number_format($product->adjust_qty,2); ?></td>
        <td  align="right"><?php echo number_format($product->adjust_price,2); ?></td>
        <td  align="right"><?php echo number_format($product->adjust_line_total_price,2); ?></td>
    </tr>
    <?php 
        $total_qty += $product->adjust_qty;
        $total_price  += $product->adjust_line_total_price;
    }}  ?>
    </tbody>
    <tfoot>
        <tr>
            <td align="right" colspan="2"><b>Total :</b> </td>
            <td id="td_grand_qty_summary" align="right"><b><?php echo number_format($total_qty,2); ?></b></td>
            <td></td>
            <td id="td_grand_total_summary"  align="right"><b><?php echo number_format($total_price,2); ?></b></td>
        </tr>
    </tfoot>
</table>

<?php } ?>

<i>Generated by: <?php echo $this->session->user_fullname; ?></i><br>
<i>Generated on: <?php date_default_timezone_set("Asia/Manila") ; echo date("Y-m-d h:i:sa") ?></i>


<script> window.print();</script>